---
- hosts: localhost
  connection: local
  # become: yes
  tasks:
    - block:
      - name: Get Username
        pause:
          prompt: "Give your username"
        register: prompt
        no_log: yes
        run_once: yes
        #tags: 
        #  - [my_role_using_user_pass]
      - name: Set Fact Username
        set_fact:
          username: "{{prompt.user_input}}"
        no_log: yes
        run_once: yes
        #tags: 
        #  - [my_role_using_user_pass]
      - name: Get Password
        pause:
          prompt: "Give your password"
          echo: no
        register: prompt
        no_log: yes
        run_once: yes
        #tags: 
        #  - [my_role_using_user_pass]
      - name: Set Fact Password
        set_fact:
          password: "{{prompt.user_input}}"
        no_log: yes
        run_once: yes
        #tags: 
        #  - [my_role_using_user_pass]
      rescue:
        - debug:
            msg: 'I caught an error, can do stuff here to fix it, :-)'
          #tags: 
          #  - [my_role_using_user_pass]
  post_tasks:
    # Main Task
  #  - name: "MAIN TASK: debug promts" 
  #    include_role:
  #      name: "my_role_using_user_pass"
  #      tasks_from: main.yml
  #    vars:
  #      username: "{{ username }}"
  #      password: "{{ password }}"
  #    tags: 
  #      - [my_role_using_user_pass]
    - name: Debug Username Variable (in role).
      debug:
        msg: "Username argument = {{ username }}"

    - name: Debug Password Variable (in role).
      debug:
        msg: "Password argument = {{ password }}"
